using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

#nullable enable

namespace GDMENUCardManager.Core
{
    public class ExportFileManager
    {
        private string backingFilePath;

        public ExportFileManager(string filePath)
        {
            backingFilePath = filePath;
        }

        public async Task WriteItems(IEnumerable<GdItem> items)
        {
            await using var writer = File.Create(backingFilePath);
            if (writer == null)
                return;

            var exportFile = new ExportFile_v1(items);
            await JsonSerializer.SerializeAsync(writer, exportFile);
        }

        public async Task<ExportFile_v1?> ReadItems()
        {
            await using var reader = File.OpenRead(backingFilePath);
            if (reader == null)
                return null;
            return await JsonSerializer.DeserializeAsync<ExportFile_v1>(reader);
        }
    }

    public class ExportFile_v1
    {
        public static readonly int k_Version = 1;

        [JsonInclude]
        public readonly int Version = k_Version;

        [JsonInclude]
        public string Info = "Generated by GDMENUCardManager";

        [JsonInclude]
        public List<GdItem> ItemList = new List<GdItem>();

        public ExportFile_v1() { }

        public ExportFile_v1(IEnumerable<GdItem> itemList)
        {
            ItemList.AddRange(itemList);
        }
    }

}

#nullable restore
